const rotor1permutation = [
  ['a', 'e'],
  ['b', 'k'],
  ['c', 'm'],
  ['d', 'f'],
  ['e', 'l'],
  ['f', 'g'],
  ['g', 'd'],
  ['h', 'q'],
  ['i', 'v'],
  ['j', 'z'],
  ['k', 'n'],
  ['l', 't'],
  ['m', 'o'],
  ['n', 'w'],
  ['o', 'y'],
  ['p', 'h'],
  ['q', 'x'],
  ['r', 'u'],
  ['s', 's'],
  ['t', 'p'],
  ['u', 'a'],
  ['v', 'i'],
  ['w', 'b'],
  ['x', 'r'],
  ['y', 'c'],
  ['z', 'j']
];
const rotor2permutation = [
  ['a', 'a'],
  ['b', 'j'],
  ['c', 'd'],
  ['d', 'k'],
  ['e', 's'],
  ['f', 'i'],
  ['g', 'r'],
  ['h', 'u'],
  ['i', 'x'],
  ['j', 'b'],
  ['k', 'l'],
  ['l', 'h'],
  ['m', 'w'],
  ['n', 't'],
  ['o', 'm'],
  ['p', 'c'],
  ['q', 'q'],
  ['r', 'g'],
  ['s', 'z'],
  ['t', 'n'],
  ['u', 'p'],
  ['v', 'y'],
  ['w', 'f'],
  ['x', 'v'],
  ['y', 'o'],
  ['z', 'e']
];
const rotor3permutation = [
  ['a', 'b'],
  ['b', 'd'],
  ['c', 'f'],
  ['d', 'h'],
  ['e', 'j'],
  ['f', 'l'],
  ['g', 'c'],
  ['h', 'p'],
  ['i', 'r'],
  ['j', 't'],
  ['k', 'x'],
  ['l', 'v'],
  ['m', 'z'],
  ['n', 'n'],
  ['o', 'y'],
  ['p', 'e'],
  ['q', 'i'],
  ['r', 'w'],
  ['s', 'g'],
  ['t', 'a'],
  ['u', 'k'],
  ['v', 'm'],
  ['w', 'u'],
  ['x', 's'],
  ['y', 'q'],
  ['z', 'o']
];
const reflectorpermutation = [
  ['a', 'y'],
  ['b', 'r'],
  ['c', 'u'],
  ['d', 'h'],
  ['e', 'q'],
  ['f', 's'],
  ['g', 'l'],
  ['i', 'p'],
  ['j', 'x'],
  ['k', 'n'],
  ['m', 'o'],
  ['t', 'z'],
  ['v', 'w']
];
const plugboardpermutation = [
  ['a', 'd'],
  ['c', 'n'],
  ['e', 't'],
  ['f', 'l'],
  ['g', 'i'],
  ['j', 'v'],
  ['k', 'z'],
  ['p', 'u'],
  ['q', 'y'],
  ['w', 'x']
];
module.exports = {
  plugboardpermutation: plugboardpermutation,
  reflectorpermutation: reflectorpermutation,
  rotor1permutation: rotor1permutation,
  rotor2permutation: rotor2permutation,
  rotor3permutation: rotor3permutation
};
